import { Menu, Moon, Sun, X } from 'lucide-react';
import { useState } from 'react';
import type { Copy, Language } from '../../data/translations';
import { useTheme } from '../../hooks/useTheme';
export default function Navbar({t,language,change}:{t:Copy;language:Language;change:(l:Language)=>void}){
 const [open,setOpen]=useState(false); const {theme,toggle}=useTheme(); const links=[['about',t.nav.about],['mission',t.nav.mission],['values',t.nav.values],['services',t.nav.services],['contact',t.nav.contact]];
 const go=(id:string)=>{document.getElementById(id)?.scrollIntoView({behavior:'smooth'});setOpen(false)};
 return <header className="fixed top-0 z-50 w-full px-4 pt-4"><nav className="mx-auto flex max-w-7xl items-center justify-between rounded-2xl border border-slate-200/80 bg-white/90 px-5 py-3 shadow-sm backdrop-blur-xl dark:border-white/10 dark:bg-[#07111f]/90"><button onClick={()=>go('top')} className="flex items-center gap-3" aria-label="Babr Capital"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#c8923e] text-xl text-white">♜</span><span className="text-left leading-none"><b className="block text-lg tracking-tight">BABR</b><small className="text-[10px] font-bold tracking-[.28em] text-[#c8923e]">CAPITAL</small></span></button><div className="hidden items-center gap-7 md:flex">{links.map(([id,label])=><button key={id} onClick={()=>go(id)} className="text-sm font-medium text-slate-600 transition hover:text-[#b77d2d] dark:text-slate-300">{label}</button>)}</div><div className="flex items-center gap-2"><button onClick={()=>change(language==='tg'?'ru':'tg')} className="rounded-lg border border-slate-200 px-2.5 py-1.5 text-xs font-semibold dark:border-white/10">{language.toUpperCase()}</button><button onClick={toggle} className="rounded-lg border border-slate-200 p-2 dark:border-white/10" aria-label="Theme">{theme==='dark'?<Sun size={16}/>:<Moon size={16}/>}</button><button className="rounded-lg border border-slate-200 p-2 md:hidden dark:border-white/10" onClick={()=>setOpen(!open)} aria-expanded={open}>{open?<X size={19}/>:<Menu size={19}/>}</button></div></nav>{open&&<div className="mx-auto mt-2 max-w-7xl rounded-2xl border border-slate-200 bg-white p-4 shadow-xl dark:border-white/10 dark:bg-[#0b1829]">{links.map(([id,label])=><button key={id} onClick={()=>go(id)} className="block w-full rounded-xl px-4 py-3 text-left text-sm font-medium hover:bg-slate-100 dark:hover:bg-white/5">{label}</button>)}</div>}</header>;
}
